[package]
name = "ift-chatbot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch-irc = "*"
tokio = {version = "1.8.0", features = ["rt-multi-thread", "macros", "full"]}